# Dagster Helm chart values for local PoC

dagster:
  image:
    repository: dagster-repo
    tag: latest
    pullPolicy: IfNotPresent

  # Enable the webserver
  webserver:
    service:
      type: NodePort
      nodePort: 30000  # Adjust if needed
    enableReadOnly: false

  # Logging configuration
  logs:
    level: INFO

runLauncher:
  type: "K8sRunLauncher"

  config:
    jobNamespace: dagster-poc
    imagePullPolicy: IfNotPresent
    dagsterK8sJobConfig:
      image: dagster-repo:latest
      namespace: dagster-poc
      envConfigMaps: []
      envSecrets: []
      volumeMounts:
        - name: bronze-volume
          mountPath: /data/bronze
        - name: silver-volume
          mountPath: /data/silver
        - name: gold-volume
          mountPath: /data/gold
      volumes:
        - name: bronze-volume
          persistentVolumeClaim:
            claimName: bronze-pvc
        - name: silver-volume
          persistentVolumeClaim:
            claimName: silver-pvc
        - name: gold-volume
          persistentVolumeClaim:
            claimName: gold-pvc

# Optional: expose Dagit logs
celeryK8s:
  enabled: false

postgresql:
  enabled: true

redis:
  enabled: true
